### ISSUE TITLE
mwindows mode

### ISSUE THREAD

**Issue by AlbertShown** [webui-dev/nim-webui#1]
I test the Nim wrapper. It's working perfectly 👍
I suggest adding `-mwindows` into the linking command in `bindings.nim` to hide the terminal window in the final executable.

![image](https://user-images.githubusercontent.com/116365846/225048189-9fe6c0bd-7325-4064-83f4-9be455e205b5.png)

**Comment by neroist** [comment]
Thank you, I'm glad you like it and its working! No need for `-mwindows` however, you can do that with `--app:gui`.
