### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/nim-webui#12]
I suggest removing the `website` folder and keep it only in the `webui` repo, because it has the FTP auto deploy so we can have only one official online documentation that has all the APIs.

https://webui.me/docs/#/

**Comment by neroist** [comment]
There is no "`website`" folder, do you mean `docs`?

**Comment by hassandraga** [comment]
Sorry. I mean `webui/website`.
But this means removing the sub-module `webui`. And make the Nim wrapper use the static prebuilt libraries as I did for the Go wrapper. This will make the repo smaller and compile faster. Just a suggestion, you can keep the repo as it is if you like it.

**Comment by neroist** [comment]
I'd like to keep the repo as it is. The static libraries are easily accessible.

**Comment by hassandraga** [comment]
Sure 👍
