### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/nim-webui#13]
I suggest we keep all repos in the same version. For example, WebUI is now on `v2.3.0`, so all repo releases should be on the same version `v2.3.0`. And if any bug fix happens only on that repo, then we publish `2.3.0.1`, `2.3.0.2` etc... I did that with Go and Python so I can easily know what version of the WebUI library is used.

**Comment by hassandraga** [comment]
@AlbertShown, @malisipi.

**Comment by AlbertShown** [comment]
@neroist I strongly recommend using the same versioning as WebUI, so the latest WebUI is `v2.3.0`, meaning the next Nim-WebUI version should be `v2.3.0`. 

[2] --> Major version
[3] -->New features
[0] -->Bug fix

Any fix that comes later in Nim-WebUI will up the last digit, `v2.3.1`, `v2.3.2` etc... or `v2.3.0.1`, `v2.3.0.2`, whatever you prefer.
