### ISSUE TITLE
Some thought about crashes when calling js from Nim

### ISSUE THREAD

**Issue by clzls** [webui-dev/nim-webui#15]
Similar to #5 , I went into some crashes when working with `hello_world.nim` using Nimble package.
In devel mode it crashes silently when clicked, in release mode it works but sometimes it still crashes.
I tried to change `webui.nim:261` from
```
data = buffer.join().strip(leading = false, chars = {'\x00'})
```
to
```
data = $(cast[cstring](addr buffer[0]))
```
Then it seems to work smoothly, with `thread:off`. Not tested much and not using nightly build, but I want to note it here for others who is willing to make further investigations about it.

My env: Nim Compiler Version 1.6.12 [Windows: amd64]

**Comment by neroist** [comment]
I've already opened a PR but I think it would be better if you opened one instead.

**Comment by clzls** [comment]
Some other thought: There are some calls returning webui-managed buffers, like `encode`. Would it be better if we copy the data to a Nim-managed `string` (by `$`) and destroy the returned buffers immediately? 😄

**Comment by AlbertShown** [comment]
I agree @clzl 👍
We should not forget to free the WebUI buffer using `webui_free()`

WebUI uses a custom memory management to allocate and free resources, so `webui_free()` will never cause a crash.

**Comment by neroist** [comment]
> Some other thought: There are some calls returning webui-managed buffers, like `encode`. Would it be better if we copy the data to a Nim-managed `string` (by `$`) and destroy the returned buffers immediately? 😄

https://github.com/webui-dev/nim-webui/commit/b26d95c8b0246bc8a0ac89e31dee31ef7b748615 🎉
