### ISSUE TITLE
Frontend framework support

### ISSUE THREAD

**Issue by griffith1deady** [webui-dev/nim-webui#18]
See this: https://github.com/webui-dev/webui/issues/109
I tried to do as I was advised by @AlbertShown, or rather change the path imports of all js/and css scripts in the html file to out/path instead of path, but it had exactly no effect.

Error receiving script files for current html
![image](https://github.com/webui-dev/nim-webui/assets/71380746/05381343-0dbb-4e7d-b4a5-77da14c12773)
But this script's located right
![image](https://github.com/webui-dev/nim-webui/assets/71380746/3e4c59ff-3a07-44d1-9fd2-0f59e3b520e1)

Right now my page looks like this when I export HTML from React through NextJS
![image](https://github.com/webui-dev/nim-webui/assets/71380746/2211f6e7-474a-432f-ac14-c747a0bcc64f)
But it should be like this:
![image](https://github.com/webui-dev/nim-webui/assets/71380746/d51610f8-33db-4ad1-8e84-a791a2a6c9ec)

Exported this page to github pages is: https://griffith1deady.github.io/languages

Minimal code for error is:

```nim
import std/os, webui

var window: Window

proc main = 
  window = newWindow(1)
  window.runtime = NodeJs
  window.show("languages.html")
  wait()

setCurrentDir(currentSourcePath().parentDir() & "/out")

main()
```

All source files with pages & resources, more precisely exporting my site https://github.com/griffith1deady/griffith1deady.github.io packed in an archive:
[NIM.zip](https://github.com/webui-dev/nim-webui/files/11576240/NIM.zip)

Also, you may notice some visual differences between my resources and those on the work site: all this is because I just used earlier commits.

***Do I think something is just blocking the distribution of files?***

**Comment by griffith1deady** [comment]
You may see errors on other pages, too, if you change the file name to one not edited under out/

**Comment by AlbertShown** [comment]
Thank you for the package, I can reproduce the issue.
I'm investigating.

**Comment by AlbertShown** [comment]
`nim -d:webuiLog c test.nim`
`./test`

```
[User] webui_new_window_id([1])...
[Core]          WebUI v2.3.0
[Core]          _webui_init()...
. . .
[Core]          _webui_file_exist([XXX/out/out/_next/static/css/5df3faa623ded248.css])...
```

`/out/out/` does not exist.
I'm looking how to fix it...

**Comment by griffith1deady** [comment]
If you put all the resources in out/out, that won't work either.
The same goes for all the other pages, even if you do something like this:
![image](https://github.com/webui-dev/nim-webui/assets/71380746/4fee127e-5688-41b5-9031-6d6dab26c9b6)

**Comment by griffith1deady** [comment]
![image](https://github.com/webui-dev/nim-webui/assets/71380746/cd5099a0-e24a-42e7-90c6-4ca6394226c5)
VSCode can find the file, but WebUI cannot.

**Comment by griffith1deady** [comment]
I have to answer that in the beginning it just couldn't find the files, but now it's blocking access/syntax error when reading them.
![image](https://github.com/webui-dev/nim-webui/assets/71380746/39370b8e-9842-49da-9599-664cdae3c161)

**Comment by AlbertShown** [comment]
![image](https://github.com/webui-dev/nim-webui/assets/116365846/119d5150-3a0c-48b8-a111-aa87bc2f5a95)

**Try this code:**

```nim
import webui

var window: Window

proc main = 

  # Create a new window object
  window = newWindow(1)
  
  # Make NodeJs as the `.ts` and `.js` interpreter
  # The command `node` should works on your system
  # window.runtime = NodeJs
  
  # Next WebUI version will have an option to change
  # the web-server root path like this:
  # window.setRoot(currentSourcePath().parentDir() & "/out")
  # Then all resource can be loaded as "/resources..."

  # Show the new window using a local HTML file
  # The web-server root path is: "/"
  # All resources should be: "/out/resources..."
  window.show("/out/languages.html")

  # Wait until all windows get closed
  wait()

main()
```

**Comment by AlbertShown** [comment]
According to this: https://webui.me/docs/#/nim_api?id=show-window
don't forgot to add `<script src="/webui.js"></script>` at the end of your HTML files.

**Comment by griffith1deady** [comment]
Okay, thank you!
