### ISSUE TITLE
text_editor.nim says undeclared field: 'rootFolder='

### ISSUE THREAD

**Issue by retsyo** [webui-dev/nim-webui#20]
I am using nim in MSYS2+MINGW64 on windows 10 64 bits. I installed webui via `nimble install webui`

```
$ nim --version
Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-06-16
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 77beb152141f0efe4d5c93b784e42f973ba46551
active boot switches: -d:release

```

I can compile 
when I try and run `nim-webui-main\examples\hello_world.nim` without problem. But for `nim-webui-main\examples\text_editor\src\text_editor.nim`, I get  

```
C:\tmp\candel\src\text_editor.nim(43, 21) Error: undeclared field: 'rootFolder=' for type we
bui.Window [type declared in C:\Users\USER\.nimble\pkgs2\webui-2.3.0.1-4945446001c8ab19a5f
9fbcbf1d771b9da4a324e\webui.nim(13, 3)]
```

**Comment by AlbertShown** [comment]
rootFolder() is a function declared [here](https://github.com/webui-dev/nim-webui/blob/398ba306742f5e5bf7b298ab55d8b6350ef677e3/webui.nim#L353), and the last modification commit is [here](https://github.com/webui-dev/nim-webui/commit/aaecd7ea8ad6adae0d323f8e5cc98f32b403c0a8).

@neroist, any idea?

**Comment by AlbertShown** [comment]
@retsyo Just to confirm, by using `hello_world.nim`, can you compile and show the window just fine?

**Comment by neroist** [comment]
> rootFolder() is a function declared [here](https://github.com/webui-dev/nim-webui/blob/398ba306742f5e5bf7b298ab55d8b6350ef677e3/webui.nim#L353), and the last modification commit is [here](https://github.com/webui-dev/nim-webui/commit/aaecd7ea8ad6adae0d323f8e5cc98f32b403c0a8).
> 
> @neroist, any idea?

Nope. I'm working on something else but I'll test the examples using Nim 1.9 soon.

**Comment by neroist** [comment]
> I am using nim in MSYS2+MINGW64 on windows 10 64 bits. I installed webui via `nimble install webui`
> 
> ```
> $ nim --version
> Nim Compiler Version 1.9.3 [Windows: amd64]
> Compiled at 2023-06-16
> Copyright (c) 2006-2023 by Andreas Rumpf
> 
> git hash: 77beb152141f0efe4d5c93b784e42f973ba46551
> active boot switches: -d:release
> ```
> 
> I can compile when I try and run `nim-webui-main\examples\hello_world.nim` without problem. But for `nim-webui-main\examples\text_editor\src\text_editor.nim`, I get
> 
> ```
> C:\tmp\candel\src\text_editor.nim(43, 21) Error: undeclared field: 'rootFolder=' for type we
> bui.Window [type declared in C:\Users\USER\.nimble\pkgs2\webui-2.3.0.1-4945446001c8ab19a5f
> 9fbcbf1d771b9da4a324e\webui.nim(13, 3)]
> ```

Weird, using 1.9.5 `text_editor` compiles and runs fine. Does your `webui.nim` define the `rootFolder=` proc?

**Comment by AlbertShown** [comment]
Probably the Nim WebUI package does not have the latest [commit](https://github.com/webui-dev/nim-webui/commit/aaecd7ea8ad6adae0d323f8e5cc98f32b403c0a8)?

**Comment by neroist** [comment]
Oh, yeah you're right it doesn't 😅. I'll also put a note that the examples use the HEAD of the gh repo, not the most recent release.

**Comment by AlbertShown** [comment]
Excellent! Thank you, @neroist for the quick fix 👍

Please, @retsyo, re-test using the latest Nim-WebUI package and let us know if it gets fixed.

**Comment by retsyo** [comment]
now `text_editor.nim` can be compiled to run without problem.

but one more thing, `ctrl+s` open a dialog to save as `html` file. Can we bind `ctrl+s` to the following code?
```nim
  window.bind("Save") do (e: Event):
    writeFile(filePath, e.data)
```

**Comment by neroist** [comment]
You'd probably have to do something with JavaScript code to bind `webui_fn('Save')` to `ctrl+s`. Maybe something like this:

```js
$(document).on('keydown', function(e){
    if(e.ctrlKey && e.which === 83){ // Check for the Ctrl key being pressed, and if the key = [S] (83)
        webui_fn('Save')
        e.preventDefault();
        return false;
    }
});
```

**Comment by neroist** [comment]
@AlbertShown Maybe WebUI should support more events than just click events for HTML elements?

**Comment by AlbertShown** [comment]
Yes, you can do it in the UI using JavaScript as @neroist mentioned 👍
