### ISSUE TITLE
Get and set window size & position

### ISSUE THREAD

**Issue by runrc** [webui-dev/nim-webui#25]
It would be very useful if we could get and set the window size and position. Can we expect this functionality to be available soon?

**Comment by hassandraga** [comment]
Set window size already exists in the main library, while getting window size can be done by running a script.
Someone needs to add this to the Nim wrapper.

```c
webui_set_size(myWindow, 800, 600);
webui_set_position(myWindow, 100, 100);
```

**Comment by runrc** [comment]
Ah OK. I believe these have already been added. Unfortunately, I get an error when trying to use version 2.4.0.0 
`.nimble/pkgs2/webui-2.4.0.0-24cbc5da9b04224b85b6b7582f461db506989670/webui.nim(118, 15) Error: undeclared field: 'data'`

**Comment by neroist** [comment]
I've updated the bindings & wrapper, this should be fixed.
