### ISSUE TITLE
write meaningful commit messages

### ISSUE THREAD

**Issue by bdjnk** [webui-dev/nim-webui#26]
As a new user trying to understand the state of this library, the commit messages have been a significant impediment. The six most recent commit messages are indicative of the difficulty.

```
updateee
beta
event
at procs
submodule
.
```

Commit messages that summarize what has changed and why would be greatly appreciated. The article [How to Write a Git Commit Message](https://cbea.ms/git-commit/) might be a useful guide to follow.

**Comment by neroist** [comment]
Thank you for this! I'll try to write better commit messages going forward.
