### ISSUE TITLE
whats is wrong

### ISSUE THREAD

**Issue by roberto170** [webui-dev/nim-webui#30]
#bind event not working

```
import webui

const ig = """
    <!DOCTYPE html>
    <html>
     <body>
        <div>hello</div>
        <button id="Bt1">ClickMe</button>
    </body>
    </html>
"""


proc main()=
    let window = newWindow()
    window.bind("Bt1") do (e : Event) : webui.exit()
    window.show(ig)
    wait()

main()
```

**Comment by roberto170** [comment]
`import webui

const ig = """
    <!DOCTYPE html>
    <html>
      <body>
         <div>hello</div>
         <button id="Bt1">ClickMe</button>
      </body>
    </html>
"""


proc main()=
    let window = newWindow()
    window.bind("Bt1") do (e : Event) : webui.exit()
    window.show(ig)
    wait()

main()`

**Comment by roberto170** [comment]
examples are working

**Comment by neroist** [comment]
You need to add `<script src="webui.js"></script>` into your html.
